# Generated by Django 4.2.3 on 2023-07-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('items', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('phoneno', models.CharField(max_length=250)),
                ('delivery', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=2500)),
            ],
        ),
    ]
